# agent_zero/meta_agent_0/core.py

import ollama
import os

class MetaAgent0:
    def __init__(self, ollama_host='http://localhost:11434', readme_path='0README.txt', default_model='orca-mini'):
        """
        Initializes Meta Agent 0.

        Args:
            ollama_host (str): The host address for the Ollama service.
            readme_path (str): The path to the 0README.txt file.
            default_model (str): The default Ollama model to use for explanations.
        """
        self.readme_path = readme_path
        self.ollama_client = ollama.Client(host=ollama_host)
        self.default_model = default_model
        print(f"MetaAgent0 initialized. README path: {os.path.abspath(self.readme_path)}, Ollama host: {ollama_host}, Default model: {self.default_model}")

    def get_readme_content(self):
        """
        Reads and returns the content of the 0README.txt file.
        Returns an empty string if the file is not found or an error occurs.
        """
        try:
            # Path relative to WORKDIR /app if 0README.txt is copied there.
            with open(self.readme_path, 'r', encoding='utf-8') as f:
                content = f.read()
            print(f"Successfully read content from {os.path.abspath(self.readme_path)}.")
            return content
        except FileNotFoundError:
            # Fallback for local testing: try path relative to this file's directory, up to project root.
            project_root_readme_path = os.path.join(os.path.dirname(__file__), '..', '..', '0README.txt')
            try:
                with open(project_root_readme_path, 'r', encoding='utf-8') as f:
                    content = f.read()
                # Update self.readme_path to the found path for consistency in logging
                self.readme_path = project_root_readme_path
                print(f"Successfully read content from {os.path.abspath(self.readme_path)} (fallback path).")
                return content
            except FileNotFoundError:
                print(f"Error: {self.readme_path} (and fallback) not found.")
                return "Error: 0README.txt not found at expected locations."
            except Exception as e:
                print(f"Error reading {project_root_readme_path} (fallback): {e}")
                return f"Error reading {project_root_readme_path}."
        except Exception as e:
            print(f"Error reading {self.readme_path}: {e}")
            return f"Error reading {self.readme_path}."

    def explain_readme_section(self, section_query, model=None):
        """
        Uses Ollama to explain a section or answer a query about the README.

        Args:
            section_query (str): A query, topic, or section name from the README to explain.
            model (str, optional): The Ollama model to use. Defaults to self.default_model.

        Returns:
            str: An explanation generated by Ollama.
        """
        readme_content = self.get_readme_content()
        if "Error:" in readme_content: # Check if reading README failed
            return f"Could not explain README section due to an error reading the README: {readme_content}"

        current_model = model if model else self.default_model

        # Corrected prompt: Using concatenation and escaped quotes for clarity
        prompt_header = "You are an AI assistant designed to help users understand a project based on its README file.\n"
        prompt_header += "The project's README content is provided below.\n"
        prompt_header += "Please answer the user's query or explain the requested section clearly and concisely.\n\n"
        prompt_query = f"User's Query/Section to Explain: \"{section_query}\"\n\n"
        prompt_readme_section = "Project README Content:\n---\n" + readme_content + "\n---\n\n"
        prompt_footer = f"Based on the README, provide your explanation for the query: \"{section_query}\""

        full_prompt = prompt_header + prompt_query + prompt_readme_section + prompt_footer

        print(f"Querying Ollama (model: {current_model}) about: {section_query}")
        try:
            response = self.ollama_client.chat(
                model=current_model,
                messages=[{'role': 'user', 'content': full_prompt}]
            )
            return response['message']['content']
        except Exception as e:
            print(f"Error interacting with Ollama (model: {current_model}): {e}")
            error_message = f"Error: Could not get explanation from Ollama (model: {current_model})."
            if hasattr(e, 'response') and e.response is not None:
                try:
                    ollama_error = e.response.json()
                    error_detail = ollama_error.get('error', str(e))
                    # Check for model not found error specifically
                    if "model not found" in error_detail.lower() or "models are not available" in error_detail.lower():
                        error_message += f" The model '{current_model}' may not be pulled or available in Ollama. Please ensure the model is pulled (e.g. `ollama pull {current_model}`)."
                    else:
                        error_message += f" Server said: {error_detail}"
                except ValueError: # If response is not JSON
                    error_message += f" Status: {e.response.status_code}. Response: {e.response.text}"
            else:
                error_message += f" Detail: {str(e)}"
            return error_message

if __name__ == '__main__':
    # Example usage (for testing purposes)
    # This assumes Ollama server is running.
    # And 0README.txt is in the root of the project.

    # print("Attempting to run MetaAgent0 example...")
    # meta_agent = MetaAgent0(default_model='orca-mini') # Specify your desired default model

    # readme_text = meta_agent.get_readme_content()
    # print(f"Retrieved README content (first 100 chars): {readme_text[:100]}...\n")

    # if "Error:" not in readme_text:
    #    # Test with default model
    #    explanation_default = meta_agent.explain_readme_section("Key Features")
    #    print(f"Ollama's explanation (default model - {meta_agent.default_model}):\n{explanation_default}\n")

    #    # Test with a specific model (if available, e.g., 'mistral')
    #    # Make sure 'mistral' is pulled in your Ollama instance: `ollama pull mistral`
    #    # explanation_specific = meta_agent.explain_readme_section("Getting Started", model="mistral")
    #    # print(f"Ollama's explanation (specific model - mistral):\n{explanation_specific}\n")

    #    # Test error case for model not found
    #    # explanation_fake_model = meta_agent.explain_readme_section("Overview", model="non_existent_model_123")
    #    # print(f"Ollama's explanation (fake model):\n{explanation_fake_model}\n")
    pass
