# agent_zero/meta_agent_0/core.py

# import ollama # Replaced by LLMClient
import os
from typing import Optional # Added Optional
from ..llm_client import LLMClient
from ..config_manager import config # Use the global config instance
from ..utils.file_utils import get_project_root # For robust README path

class MetaAgent0:
    def __init__(self,
                 readme_path: Optional[str] = None,
                 default_model_override: Optional[str] = None):
        """
        Initializes Meta Agent 0.

        Args:
            readme_path (Optional[str]): Path to the 0README.txt file. If None, uses get_project_root().
            default_model_override (Optional[str]): Specific Ollama model to use for explanations, overriding config.
        """
        if readme_path:
            self.readme_path = readme_path
        else:
            # Attempt to find 0README.txt at the project root
            project_root = get_project_root()
            self.readme_path = os.path.join(project_root, "0README.txt")

        # LLMClient gets host from config_manager internally
        self.llm_client = LLMClient(host=config.get_ollama_host())

        self.default_model = default_model_override if default_model_override is not None else config.get_primary_utility_model()
        # Using utility model as default for MetaAgent0, can be changed.
        # Could also be a dedicated MetaAgent0 model in config.

        print(f"MetaAgent0 initialized. README path: {os.path.abspath(self.readme_path)}, Default model: {self.default_model}")
        print(f"  (LLMClient configured for host: {self.llm_client.host})")


    def get_readme_content(self):
        """
        Reads and returns the content of the 0README.txt file.
        Returns an empty string if the file is not found or an error occurs.
        """
        try:
            # Path relative to WORKDIR /app if 0README.txt is copied there.
            with open(self.readme_path, 'r', encoding='utf-8') as f:
                content = f.read()
            print(f"Successfully read content from {os.path.abspath(self.readme_path)}.")
            return content
        except FileNotFoundError:
            print(f"Error: README file not found at {os.path.abspath(self.readme_path)}.")
            return f"Error: README file not found at {os.path.abspath(self.readme_path)}."
        except Exception as e:
            print(f"Error reading {os.path.abspath(self.readme_path)}: {e}")
            return f"Error reading {os.path.abspath(self.readme_path)}."

    def explain_readme_section(self, section_query: str, model_override: Optional[str] = None) -> str:
        """
        Uses Ollama to explain a section or answer a query about the README.

        Args:
            section_query (str): A query, topic, or section name from the README to explain.
            model_override (str, optional): The Ollama model to use, overriding the instance's default.

        Returns:
            str: An explanation generated by Ollama, or an error message.
        """
        readme_content = self.get_readme_content()
        if readme_content.startswith("Error:"): # Check if reading README failed
            return f"Could not explain README section. Error accessing README: {readme_content}"

        current_model_to_use = model_override if model_override else self.default_model

        system_message = (
            "You are an AI assistant specialized in explaining project documentation. "
            "The user will provide a query about a project's README file, and the content of that README. "
            "Your task is to answer the user's query based *only* on the provided README content. "
            "Be clear, concise, and directly address the query."
        )

        user_prompt = (
            f"User's Query/Section to Explain: \"{section_query}\"\n\n"
            "Project README Content:\n"
            "--- BEGIN README ---\n"
            f"{readme_content}\n"
            "--- END README ---\n\n"
            f"Based *only* on the README content provided above, please explain or answer the query: \"{section_query}\""
        )

        # print(f"MetaAgent0: Querying LLM (model: {current_model_to_use}) about: '{section_query}'") # Debug

        # Use the LLMClient instance
        response = self.llm_client.call_llm(
            prompt=user_prompt,
            system_message=system_message,
            model=current_model_to_use
        )

        # LLMClient's call_llm already includes error handling and returns error messages.
        return response


if __name__ == '__main__':
    print("--- MetaAgent0 Test ---")
    # This assumes Ollama is running and the specified models are pulled.
    # It also assumes 0README.txt is at the project root.

    # To run this test effectively, ensure:
    # 1. Ollama service is running (`ollama serve &`)
    # 2. The default utility model (e.g., tinydolphin or orca-mini) is pulled.
    #    `ollama pull tinydolphin:1.1b-q4_K_M` (or whatever config.get_primary_utility_model() returns)
    # 3. `0README.txt` exists at the project root.

    # Create a dummy 0README.txt for testing if it doesn't exist or if you want a controlled test
    # For this test, we'll assume it exists as per project structure.
    # project_root_for_test = get_project_root()
    # test_readme_path = os.path.join(project_root_for_test, "0README.txt")
    # print(f"Using README for test: {test_readme_path}")
    # if not os.path.exists(test_readme_path):
    #     print(f"WARNING: Test README {test_readme_path} not found. MetaAgent0 tests might fail or be limited.")
    #     # As a fallback, create a dummy one in CWD for the test to proceed somewhat
    #     if not os.path.exists("0README.txt"):
    #         with open("0README.txt", "w") as f:
    #             f.write("# Test README\nThis is a test.\nKey Feature: Simplicity.")
    #         print("Created a dummy 0README.txt in CWD for testing.")
    #         test_readme_path = "0README.txt" # use the local dummy


    meta_agent = MetaAgent0() # Uses default README path and model from config

    print(f"\nMetaAgent0 initialized with:")
    print(f"  README Path: {os.path.abspath(meta_agent.readme_path)}")
    print(f"  Default Model: {meta_agent.default_model}")
    print(f"  LLMClient Host: {meta_agent.llm_client.host}")

    readme_sample = meta_agent.get_readme_content()
    if readme_sample.startswith("Error:"):
        print(f"\nERROR getting README content: {readme_sample}")
    else:
        print(f"\nSuccessfully read README (first 100 chars): '{readme_sample[:100].replace(chr(10), ' ')}...'")

        print("\n--- Testing explain_readme_section (using MetaAgent0 default model) ---")
        query1 = "What are the Core Principles of Agent Zero?" # Should be in 0README.txt
        explanation1 = meta_agent.explain_readme_section(query1)
        print(f"Query: '{query1}'\nExplanation:\n{explanation1}")

        print("\n--- Testing explain_readme_section with a specific model override ---")
        # Ensure this model is pulled, e.g., `ollama pull mistral:7b-instruct-q5_K_M`
        # Using a chat model here to see if it behaves differently for this task.
        override_model = config.get_primary_chat_model()
        if override_model == meta_agent.default_model: # If default utility is same as primary chat
             print(f"(Skipping override test as override model '{override_model}' is same as default.)")
        else:
            query2 = "How do I build the Docker image?" # Should be in 0README.txt
            explanation2 = meta_agent.explain_readme_section(query2, model_override=override_model)
            print(f"Query: '{query2}' (using model: {override_model})\nExplanation:\n{explanation2}")

        print("\n--- Testing with a query about a non-existent section (to see LLM's handling) ---")
        query3 = "What is the airspeed velocity of an unladen swallow?"
        explanation3 = meta_agent.explain_readme_section(query3)
        print(f"Query: '{query3}'\nExplanation:\n{explanation3}")

    print("\n--- Testing with a non-existent model (handled by LLMClient) ---")
    query_err = "Test query"
    explanation_err = meta_agent.explain_readme_section(query_err, model_override="this-model-does-not-exist-12345.gguf")
    print(f"Query: '{query_err}' (using non-existent model)\nExplanation (should be error):\n{explanation_err}")
    # Make assertion more general to account for connection errors if Ollama is not running during test
    assert "Error" in explanation_err or "Failed to connect" in explanation_err or "unexpected error" in explanation_err.lower(), \
        f"Generic error message for LLM call not as expected. Got: {explanation_err}"


    # Clean up dummy 0README.txt if it was created locally for test
    # if os.path.exists("0README.txt") and test_readme_path == "0README.txt":
    #    os.remove("0README.txt")
    #    print("Cleaned up dummy 0README.txt from CWD.")

    print("\nMetaAgent0 test finished.")
